# Update NPM depdencies

version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
      timezone: "Australia/Melbourne"
      time: "07:00"
    versioning-strategy: increase
    pull-request-branch-name:
      separator: "-"
    commit-message:
      prefix: "npm"
    labels:
      - "npm"
      - "dependencies"
